### ISSUE TITLE
Null Hypothesis for bsdfs fails when the flag PBRT_FLOAT_AS_DOUBLE is set

### ISSUE THREAD

**Issue by belalmksaid** [mmp/pbrt-v3#165] opened 2017-12-10 02:54 UTC
I ran the the pbrt_test for float and double. It passes everything for float but for double it fails 12 tests, a lot of which are sampling tests.

I have attached the test results for both float and double.

[bench32.txt](https://github.com/mmp/pbrt-v3/files/1545277/bench32.txt)
[bench64.txt](https://github.com/mmp/pbrt-v3/files/1545276/bench64.txt)

**Comment by mmp** [comment] 2017-12-18 18:37
Thanks for reporting, but this is a duplicate of #51.

**Closed by mmp** 2017-12-18 18:37 UTC
