### ISSUE TITLE
Compilation issues with Sublime Text 2 - Ninja generator

### ISSUE THREAD

**Issue by brupelo** [mmp/pbrt-v3#89] opened 2016-10-11 23:45 UTC
Steps to reproduce:
- Clone project
- `git submodule update --init --recursive`
- `mkdir build && cd build`
- `cmake .. -G "Sublime Text 2 - Project" -DCMAKE_BUILD_TYPE=Release`
- `sublime_text sublime_text PBRT-V3.sublime-project`
- Build all

And the output will be:

ninja: error: 'src/ext/zlib/Release/zlibstatic.lib', needed by 'imgtool.exe', missing and no known rule to make it

What does it mean?

**Comment by mmp** [comment] 2016-11-19 17:35
I can't reproduce this on OSX; a ninja build via cmake completes without errors. Unfortunately I don't have easy access to a Windows system, so can't be of much help debugging this.

**Comment by brupelo** [comment] 2016-11-19 18:15
Matt, mmm, the fact using cmake+ninja on macosx works out of the box but not on windows is... well, strange :) , if you got any suggestion in order to narrow this please let me know, I got windows and I could test it out.

**Comment by mmp** [comment] 2016-11-22 17:49
I found a Windows-specific issue in the cmake file that may have caused this. Could you try syncing to top of tree and see if this is fixed?

**Comment by brupelo** [comment] 2016-11-22 17:59
@mmp Hi, unfortunately that didn't do it, here's the [current output](http://screencast.com/t/NUoFIgvCX)

**Comment by mmp** [comment] 2017-12-18 18:33
Closing as "don't know how to fix / don't have enough info to proceed"

**Closed by mmp** 2017-12-18 18:33 UTC
