### ISSUE TITLE
Failed tests for Float as double

### ISSUE THREAD

**Issue by tsulej** [mmp/pbrt-v3#156] opened 2017-10-25 14:58 UTC
When Float is double following tests fail

[----------] Global test environment tear-down
[==========] 187 tests from 31 test cases ran. (301083 ms total)
[  PASSED  ] 174 tests.
[  FAILED  ] 13 tests, listed below:
[  FAILED  ] Triangle.Reintersect
[  FAILED  ] BSDFSampling.Beckmann_VA_0p5
[  FAILED  ] BSDFSampling.TR_VA_0p5
[  FAILED  ] BSDFSampling.Beckmann_std_0p5
[  FAILED  ] BSDFSampling.TR_std_0p5
[  FAILED  ] BSDFSampling.Beckmann_VA_0p2_0p1
[  FAILED  ] BSDFSampling.TR_VA_0p3_0p15
[  FAILED  ] BSDFSampling.Beckmann_std_0p2_0p1
[  FAILED  ] BSDFSampling.TR_std_0p2_0p1
[  FAILED  ] BSDFSampling.Beckmann_VA_0p4_0p3
[  FAILED  ] BSDFSampling.TR_VA_0p3
[  FAILED  ] BSDFSampling.Beckmann_std_0p2
[  FAILED  ] BSDFSampling.TR_std_0p05_0p1

13 FAILED TESTS

**Comment by mmp** [comment] 2017-10-25 17:30
Duplicate of #51

**Closed by mmp** 2017-10-25 17:30 UTC

**Comment by tsulej** [comment] 2017-10-25 19:08
oops, sorry for duplicate
